build:
    environment:
        python: '3.12'

    dependencies:
        before:
            - pip install uv
            - uv sync

    tests:
        override:
            - command: uv run pytest --cov=irc2phpbb --cov-report=xml
              coverage:
                  file: coverage.xml
                  format: py-cc
