build:
    environment:
        python: '3.12'

    dependencies:
        before:
            - pip install uv coverage
            - uv sync

    tests:
        override:
            - command: uv run pytest --cov=irc2phpbb
              coverage:
                  file: .coverage
                  format: py-cc
